### ISSUE TITLE
setPassword does nothing.

### ISSUE THREAD

**Issue by msolhao** [comodojo/zip#3]
Hello, when using the **setPassword()** method to extract a protected zip file, the extraction fails with code 26.
This is caused because your forget to invoke the **ZipArchive::setPassword()** method.
In your current release you only set the password to its property, nothing more.

This is part of your extract method:

``` php
/**
     * Extract files from zip archive
     *
     * @param   string  $destination    Destination path
     * @param   mixed   $files          (optional) a filename or an array of filenames
     *
     * @return  bool
     * @throws  \Comodojo\Exception\ZipException
     */
    public function extract($destination, $files = null) {

        ...

        $extract = $this->zip_archive->extractTo($destination, $file_matrix);

        if ( $extract === false ) throw new ZipException(self::getStatus($this->zip_archive->status));

        return true;

    }
```

and it should be like this:

``` php
/**
     * Extract files from zip archive
     *
     * @param   string  $destination    Destination path
     * @param   mixed   $files          (optional) a filename or an array of filenames
     *
     * @return  bool
     * @throws  \Comodojo\Exception\ZipException
     */
    public function extract($destination, $files = null) {

        ...

        if (!empty($this->password)) {
            $this->zip_archive->setPassword($this->password);
        }

        $extract = $this->zip_archive->extractTo($destination, $file_matrix);

        if ( $extract === false ) throw new ZipException(self::getStatus($this->zip_archive->status));

        return true;

    }
```

This will fix the problem.

Be carefull, the ZipArchive::setPassword() was introduced in php 5.6 so your package requirements should be changed changed to >= 5.6.0

**Comment by marcogiovinazzi** [comment]
You're right: it is a bug and package should require php >= 5.6.0.
Anyway, I'd like to keep it compatible with lower php versions, so I will remove this feature from current branch and publish a patch (2.0.2). At the same time, I will release 2.1.0 version that will include your patch.
Thanks for the report!
