### ISSUE TITLE
set save path

### ISSUE THREAD

**Issue by wyklif** [comodojo/zip#4]
Hello, great package. However i dont see any method to save to a specified path please advice thanks.

**Comment by marcogiovinazzi** [comment]
Thanks!

The destination path can be specified in [open/create ](https://github.com/comodojo/zip#basic-operations) static methods, if that's what you mean.

For example, assuming you are creating a zip archive `file.zip` that should be saved in `/tmp/my/path`:

`$result = Zip::create('/tmp/my/path/file.zip')->add('/path/to/my/file')->close();`
